version: '3.1'

services:
  askepro_react:
    container_name: askepro_react
    image: node:14
    restart: always
    stdin_open: true
    working_dir: /app
    command: bash -c "npm install && npm start"
    volumes:
      - .:/app
    ports:
      - "3000:3000"